ALTER TABLE plans ADD COLUMN rpm_limit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE plans ADD COLUMN tpm_limit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE plans ADD COLUMN concurrency_limit INTEGER NOT NULL DEFAULT 0;