import { Bug, Sparkles, Gauge, BookOpen, Wrench, Package, Circle } from "lucide-react";

// ── Types ────────────────────────────────────────────────────────────
interface ChangelogEntry {
  scope: string;
  description: string;
  commit?: string;
}

interface ChangelogSection {
  category: string;
  entries: ChangelogEntry[];
}

interface ChangelogRelease {
  version: string;
  date: string;
  sections: ChangelogSection[];
}

// ── Category metadata ────────────────────────────────────────────────
const categoryMeta: Record<
  string,
  { icon: typeof Bug; label: string; className: string }
> = {
  "bug fixes": {
    icon: Bug,
    label: "Bug Fixes",
    className: "text-red-600 dark:text-red-400",
  },
  features: {
    icon: Sparkles,
    label: "Features",
    className: "text-accent-600 dark:text-accent-400",
  },
  performance: {
    icon: Gauge,
    label: "Performance",
    className: "text-accent-600 dark:text-accent-400",
  },
  documentation: {
    icon: BookOpen,
    label: "Documentation",
    className: "text-[var(--text-muted)]",
  },
  ci: {
    icon: Wrench,
    label: "CI",
    className: "text-[var(--text-muted)]",
  },
  refactor: {
    icon: Package,
    label: "Refactor",
    className: "text-[var(--text-muted)]",
  },
};

function getCategoryMeta(category: string) {
  const key = category.toLowerCase();
  return (
    categoryMeta[key] ?? {
      icon: Circle,
      label: category,
      className: "text-[var(--text-muted)]",
    }
  );
}

// ── Parser ───────────────────────────────────────────────────────────
function parseChangelog(raw: string): ChangelogRelease[] {
  if (!raw) return [];

  // Strip HTML comments (e.g. <!-- generated by git-cliff -->)
  const cleaned = raw.replace(/<!--[\s\S]*?-->/g, "").trim();
  const lines = cleaned.split("\n");
  const releases: ChangelogRelease[] = [];

  let current: ChangelogRelease | null = null;
  let currentSection: ChangelogSection | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    // Skip the top-level "# Changelog" header
    if (/^#\s+Changelog/i.test(trimmed)) continue;

    // ## [version] — date  OR  ## version — date
    const versionMatch = trimmed.match(
      /^##\s+\[?v?([\d.]+)\]?\s*(?:—|--|–|-)\s*(.*)/
    );
    if (versionMatch) {
      current = {
        version: versionMatch[1],
        date: versionMatch[2].trim(),
        sections: [],
      };
      releases.push(current);
      currentSection = null;
      continue;
    }

    // ### Category
    const catMatch = trimmed.match(/^###\s+(.+)/);
    if (catMatch && current) {
      currentSection = { category: catMatch[1].trim(), entries: [] };
      current.sections.push(currentSection);
      continue;
    }

    // - **scope:** description(hash)  OR  - description(hash)
    const itemMatch = trimmed.match(
      /^[-*]\s+(?:\*\*(.+?):\*\*\s*)?(.+?)(?:\(([a-f0-9]{7,})\))?$/
    );
    if (itemMatch && currentSection) {
      currentSection.entries.push({
        scope: itemMatch[1] || "",
        description: itemMatch[2].trim(),
        commit: itemMatch[3],
      });
      continue;
    }

    // Fallback: any other "- text" line
    const fallbackMatch = trimmed.match(/^[-*]\s+(.+)/);
    if (fallbackMatch && currentSection) {
      currentSection.entries.push({
        scope: "",
        description: fallbackMatch[1].trim(),
      });
    }
  }

  return releases;
}

// ── Component ────────────────────────────────────────────────────────
export function ChangelogMarkdown({
  changelog,
  compact = false,
}: {
  changelog: string;
  compact?: boolean;
}) {
  const releases = parseChangelog(changelog);

  if (releases.length === 0) {
    // Fallback: render as plain text if parser found nothing
    return (
      <p className="whitespace-pre-wrap text-xs leading-relaxed text-[var(--text)]">
        {changelog}
      </p>
    );
  }

  return (
    <div className={compact ? "space-y-3 text-[var(--text)]" : "space-y-5"}>
      {releases.map((rel, releaseIndex) => (
        <div key={rel.version} className={compact && releaseIndex > 0 ? "border-t border-[var(--border)] pt-3" : undefined}>
          {/* Version header */}
          <div className="mb-2 flex min-w-0 items-center gap-2">
            <span className="inline-flex shrink-0 items-center rounded-md bg-accent-100 px-2 py-0.5 font-mono text-xs font-semibold text-accent-700 dark:bg-accent-900/40 dark:text-accent-300">
              v{rel.version}
            </span>
            {rel.date && (
              <span className="min-w-0 truncate text-xs text-[var(--text-muted)]">{rel.date}</span>
            )}
          </div>

          {/* Sections */}
          {rel.sections.length > 0 ? (
            <div className={compact ? "space-y-2" : "space-y-3"}>
              {rel.sections.map((sec) => {
                const meta = getCategoryMeta(sec.category);
                const Icon = meta.icon;
                return (
                  <div key={sec.category}>
                    <div className="mb-1 flex items-center gap-1.5">
                      <Icon className={`h-3.5 w-3.5 ${meta.className}`} />
                      <span
                        className={`text-xs font-semibold uppercase tracking-wider ${meta.className}`}
                      >
                        {meta.label}
                      </span>
                    </div>
                    <ul className={compact ? "space-y-1" : "space-y-1"}>
                      {sec.entries.map((entry, i) => (
                        <li
                          key={i}
                          className="flex min-w-0 items-start gap-1.5 text-xs leading-relaxed text-[var(--text)]"
                        >
                          <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-[var(--text-muted)]" />
                          <span className="min-w-0 break-words">
                            {entry.scope && (
                              <span className="mr-1 inline-flex items-center rounded bg-[var(--bg-subtle)] px-1 py-px font-mono text-[10px] font-medium text-[var(--text-muted)]">
                                {entry.scope}
                              </span>
                            )}
                            {entry.description}
                            {entry.commit && (
                              <span className="ml-1 whitespace-nowrap font-mono text-[10px] text-[var(--text-muted)]">
                                ({entry.commit})
                              </span>
                            )}
                          </span>
                        </li>
                      ))}
                    </ul>
                  </div>
                );
              })}
            </div>
          ) : (
            <p className="text-xs text-[var(--text-muted)] italic">
              No detailed changes listed.
            </p>
          )}
        </div>
      ))}
    </div>
  );
}
